In [ ]:
# @title Assigning A+ elements to variables
element_data = {
    "Li": {
        "Ionic radius (pm)": 76,
        "Ionization energy (kJ/mol)": 520.2,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 164.1, # Atomic polarizability of neutral Li (a.u.) - A more common value for neutral Li. The provided value seems to be for Li+ ion.
        "Atom formation enthalpy (kJ/mol)": 161, # Standard enthalpy of atomization for Li
        "Atomic number": 3
    },
    "Na": {
        "Ionic radius (pm)": 102, # Na+
        "Ionization energy (kJ/mol)": 495.8,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 162.88, # Atomic polarizability of neutral Na (a.u.)
        "Atom formation enthalpy (kJ/mol)": 108.4, # Standard enthalpy of atomization for Na
        "Atomic number": 11
    },
    "K": {
        "Ionic radius (pm)": 138, # K+
        "Ionization energy (kJ/mol)": 418.8,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 290.1, # Atomic polarizability of neutral K (a.u.) - Based on trends and comparisons with other alkali metals. Specific search results were less direct for a single value.
        "Atom formation enthalpy (kJ/mol)": 89, # Standard enthalpy of atomization for K
        "Atomic number": 19
    },
    "Rb": {
        "Ionic radius (pm)": 152, # Rb+
        "Ionization energy (kJ/mol)": 403.0,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 319.2, # Atomic polarizability of neutral Rb (a.u.) - Based on trends and comparisons with other alkali metals. Specific search results were less direct for a single value.
        "Atom formation enthalpy (kJ/mol)": 81, # Standard enthalpy of atomization for Rb
        "Atomic number": 37
    },
    "Cs": {
        "Ionic radius (pm)": 167, # Cs+
        "Ionization energy (kJ/mol)": 375.7,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 400, # Atomic polarizability of neutral Cs (a.u.) - Approximate value found in research
        "Atom formation enthalpy (kJ/mol)": 76, # Standard enthalpy of atomization for Cs
        "Atomic number": 55
    },
    "Cu": {
        "Ionic radius (pm)": 73, # Cu+
        "Ionization energy (kJ/mol)": 745.5,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 48.12, # Static dipole polarizability of neutral Cu (a.u.)
        "Atom formation enthalpy (kJ/mol)": 338, # Standard enthalpy of atomization for Cu
        "Atomic number": 29
    },
    "Au": {
        "Ionic radius (pm)": 137, # Au3+ or Au+ depending on source
        "Ionization energy (kJ/mol)": 890.1,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 36.68, # Static dipole polarizability of neutral Au (a.u.)
        "Atom formation enthalpy (kJ/mol)": 326, # Standard enthalpy of atomization for Au
        "Atomic number": 79
    },
    "Ag": {
        "Ionic radius (pm)": 126, # Ag+
        "Ionization energy (kJ/mol)": 731.0,
        "Valence electron number": 1,
        "Polarizability (a.u.)": 50.97, # Static dipole polarizability of neutral Ag (a.u.)
        "Atom formation enthalpy (kJ/mol)": 285, # Standard enthalpy of atomization for Ag
        "Atomic number": 47
    }
}

In [ ]:
# @title Assigning B2+ elements to variables
element_data_2 = {
    "Pb": {
        "Ionic radius (pm)": 119,
        "Electronegativity (Pauling)": 2.33,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 48.0, # Static dipole polarizability of neutral Pb (a.u.) - Value from literature
        "Atom formation enthalpy (kJ/mol)": 195, # Standard enthalpy of atomization for Pb (from WebElements/Wired Chemist)
        "Atomic number": 82
    },
    "Sn": {
        "Ionic radius (pm)": 118, # Sn2+
        "Electronegativity (Pauling)": 1.96,
        "Valence electron number": 4,
        "Polarizability (a.u.)": 50.0, # Static dipole polarizability of neutral Sn (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 302, # Standard enthalpy of atomization for Sn (from WebElements)
        "Atomic number": 50
    },
    "Ge": {
        "Ionic radius (pm)": 73, # Ge4+
        "Electronegativity (Pauling)": 2.01,
        "Valence electron number": 4,
        "Polarizability (a.u.)": 37.5, # Static dipole polarizability of neutral Ge (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 377, # Standard enthalpy of atomization for Ge (from WebElements)
        "Atomic number": 32
    },
    "Be": {
        "Ionic radius (pm)": 45, # Be2+ (Source: Wired Chemist)
        "Electronegativity (Pauling)": 1.57, # (Commonly cited value)
        "Valence electron number": 2,
        "Polarizability (a.u.)": 37.7, # Static dipole polarizability of neutral Be (a.u.) - From Schwerdtfeger & Nagle tables (e.g., 2018, 2020, 2023 updates)
        "Atom formation enthalpy (kJ/mol)": 324, # Standard enthalpy of atomization for Be (from WebElements/Wired Chemist)
        "Atomic number": 4
    },
    "Mg": {
        "Ionic radius (pm)": 72, # Mg2+
        "Electronegativity (Pauling)": 1.31,
        "Valence electron number": 7,
        "Polarizability (a.u.)": 71.2, # Static dipole polarizability of neutral Mg (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 146, # Standard enthalpy of atomization for Mg (from WebElements)
        "Atomic number": 12
    },
    "Ca": {
        "Ionic radius (pm)": 100, # Ca2+
        "Electronegativity (Pauling)": 1.00,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 161, # Static dipole polarizability of neutral Ca (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 178, # Standard enthalpy of atomization for Ca (from WebElements)
        "Atomic number": 20
    },
    "Sr": {
        "Ionic radius (pm)": 118, # Sr2+
        "Electronegativity (Pauling)": 0.95,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 197, # Static dipole polarizability of neutral Sr (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 164, # Standard enthalpy of atomization for Sr (from WebElements)
        "Atomic number": 38
    },
    "Ba": {
        "Ionic radius (pm)": 135, # Ba2+
        "Electronegativity (Pauling)": 0.89,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 272, # Static dipole polarizability of neutral Ba (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 182, # Standard enthalpy of atomization for Ba (from WebElements)
        "Atomic number": 56
    },
    "Mn": {
        "Ionic radius (pm)": 67, # Mn2+ (common)
        "Electronegativity (Pauling)": 1.55,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 60.8, # Static dipole polarizability of neutral Mn (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 281, # Standard enthalpy of atomization for Mn (from WebElements)
        "Atomic number": 25
    },
    "Fe": {
        "Ionic radius (pm)": 70, # Fe2+ (common) or 60 (Fe3+)
        "Electronegativity (Pauling)": 1.83,
        "Valence electron number": 8,
        "Polarizability (a.u.)": 56.0, # Static dipole polarizability of neutral Fe (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 415, # Standard enthalpy of atomization for Fe (from WebElements)
        "Atomic number": 26
    },
    "Co": {
        "Ionic radius (pm)": 65, # Co2+ (common) or 61 (Co3+)
        "Electronegativity (Pauling)": 1.88,
        "Valence electron number": 9,
        "Polarizability (a.u.)": 49.6, # Static dipole polarizability of neutral Co (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 426, # Standard enthalpy of atomization for Co (from WebElements)
        "Atomic number": 27
    },
    "Ni": {
        "Ionic radius (pm)": 69, # Ni2+
        "Electronegativity (Pauling)": 1.91,
        "Valence electron number": 10,
        "Polarizability (a.u.)": 43.0, # Static dipole polarizability of neutral Ni (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 431, # Standard enthalpy of atomization for Ni (from WebElements)
        "Atomic number": 28
    },
    "Cu": {
        "Ionic radius (pm)": 73, # Cu2+ (common oxidation state, value from WebElements/Filo)
        "Electronegativity (Pauling)": 1.90, # (From WebElements)
        "Valence electron number": 1, # Common oxidation states +1, +2
        "Polarizability (a.u.)": 46.91, # Static dipole polarizability of neutral Cu (a.u.) (Source: ACS Publications)
        "Atom formation enthalpy (kJ/mol)": 338, # Standard enthalpy of atomization for Cu (from WebElements/Vedantu)
        "Atomic number": 29
    },
    "Zn": {
        "Ionic radius (pm)": 74, # Zn2+
        "Electronegativity (Pauling)": 1.65,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 37.95, # Static dipole polarizability of neutral Zn (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 131, # Standard enthalpy of atomization for Zn (from WebElements/Wired Chemist)
        "Atomic number": 30
    },
    "Pd": {
        "Ionic radius (pm)": 86, # Pd2+
        "Electronegativity (Pauling)": 2.20,
        "Valence electron number": 10,
        "Polarizability (a.u.)": 26.14, # Static dipole polarizability of neutral Pd (a.u.) - Value from literature (e.g., Jerabek & Schwerdtfeger)
        "Atom formation enthalpy (kJ/mol)": 377, # Standard enthalpy of atomization for Pd (from WebElements)
        "Atomic number": 46
    },
    "Ir": {
        "Ionic radius (pm)": 62.5, # Ir3+
        "Electronegativity (Pauling)": 2.20,
        "Valence electron number": 9, # Common oxidation states include +3, +4
        "Polarizability (a.u.)": 47.0, # Static dipole polarizability of neutral Ir (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 671, # Standard enthalpy of atomization for Ir (from WebElements)
        "Atomic number": 77
    },
    "Pt": {
        "Ionic radius (pm)": 80, # Pt2+ (common) or 77 (Pt4+)
        "Electronegativity (Pauling)": 2.28,
        "Valence electron number": 10,
        "Polarizability (a.u.)": 48.0, # Static dipole polarizability of neutral Pt (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 561, # Standard enthalpy of atomization for Pt (from literature/tables)
        "Atomic number": 78
    },
    "Te": {
        "Ionic radius (pm)": 135, # Te2-
        "Electronegativity (Pauling)": 2.1,
        "Valence electron number": 6,
        "Polarizability (a.u.)": 37.0, # Static dipole polarizability of neutral Te (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 197, # Standard enthalpy of atomization for Te (from WebElements)
        "Atomic number": 52
    },
    "Cd": {
        "Ionic radius (pm)": 95, # Cd2+
        "Electronegativity (Pauling)": 1.69,
        "Valence electron number": 2,
        "Polarizability (a.u.)": 49.65, # Static dipole polarizability of neutral Cd (a.u.) - Experimental value from literature
        "Atom formation enthalpy (kJ/mol)": 112, # Standard enthalpy of atomization for Cd (from WebElements)
        "Atomic number": 48
    }
}

In [ ]:
# @title Assigning B3+ elements to variables
element_data_3 = {
    "Al": {
        "Ionic radius (pm)": 53,  # Al3+
        "Electronegativity (Pauling)": 1.61,
        "Valence electron number": 3,
        "Polarizability (a.u.)": 55.0, # Static dipole polarizability of neutral Al (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 326, # Standard enthalpy of atomization for Al (from WebElements)
        "Atomic number": 13
    },
    "Ga": {
        "Ionic radius (pm)": 76,  # Ga3+
        "Electronegativity (Pauling)": 1.81,
        "Valence electron number": 3,
        "Polarizability (a.u.)": 67.0, # Static dipole polarizability of neutral Ga (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 277, # Standard enthalpy of atomization for Ga (from WebElements)
        "Atomic number": 31
    },
    "In": {
        "Ionic radius (pm)": 94,  # In3+
        "Electronegativity (Pauling)": 1.78,
        "Valence electron number": 3,
        "Polarizability (a.u.)": 83.0, # Static dipole polarizability of neutral In (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 243, # Standard enthalpy of atomization for In (from WebElements/Wired Chemist)
        "Atomic number": 49
    },
    "Sb": {
        "Ionic radius (pm)": 76,  # Sb3+
        "Electronegativity (Pauling)": 2.05,
        "Valence electron number": 5, # Can vary
        "Polarizability (a.u.)": 55.0, # Static dipole polarizability of neutral Sb (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 262, # Standard enthalpy of atomization for Sb (from WebElements)
        "Atomic number": 51
    },
    "Bi": {
        "Ionic radius (pm)": 103, # Bi3+
        "Electronegativity (Pauling)": 2.02,
        "Valence electron number": 5, # Can vary
        "Polarizability (a.u.)": 62.0, # Static dipole polarizability of neutral Bi (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 207, # Standard enthalpy of atomization for Bi (from WebElements)
        "Atomic number": 83
    },
    "Au": {
        "Ionic radius (pm)": 137,
        "Electronegativity (Pauling)": 2.54,
        "Valence electron number": 1, # Can vary, commonly considered 1 for reactivity
        "Polarizability (a.u.)": 36.68, # Static dipole polarizability of neutral Au (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 366, # Standard enthalpy of atomization for Au (from literature/Wired Chemist)
        "Atomic number": 79
    },
    "Sc": {
        "Ionic radius (pm)": 89,  # Sc3+
        "Electronegativity (Pauling)": 1.36,
        "Valence electron number": 3,
        "Polarizability (a.u.)": 103.0, # Static dipole polarizability of neutral Sc (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 378, # Standard enthalpy of atomization for Sc (from WebElements)
        "Atomic number": 21
    },
    "Y": {
        "Ionic radius (pm)": 104, # Y3+
        "Electronegativity (Pauling)": 1.22,
        "Valence electron number": 3,
        "Polarizability (a.u.)": 137.0, # Static dipole polarizability of neutral Y (a.u.) - Value from literature/tables
        "Atom formation enthalpy (kJ/mol)": 423, # Standard enthalpy of atomization for Y (from literature/Wired Chemist)
        "Atomic number": 39
    }
}

In [ ]:
# @title Assigning X- elements to variables
element_data_4 = {
    "F": {
        "Ionic radius (pm)": 133,  # F-
        "Electronegativity (Pauling)": 3.98,
        "Valence electron number": 7,
        "Polarizability (a.u.)": 3.74, # Static dipole polarizability of neutral F (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 79.08, # Enthalpy of atomization (1/2 F2 -> F)
        "Electron affinity (kJ/mol)": -328,
        "Atomic number": 9
    },
    "Cl": {
        "Ionic radius (pm)": 181, # Cl-
        "Electronegativity (Pauling)": 3.16,
        "Valence electron number": 7,
        "Polarizability (a.u.)": 14.6, # Static dipole polarizability of neutral Cl (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 121.8, # Enthalpy of atomization (1/2 Cl2 -> Cl)
        "Electron affinity (kJ/mol)": -349,
        "Atomic number": 17
    },
    "Br": {
        "Ionic radius (pm)": 196, # Br-
        "Electronegativity (Pauling)": 2.96,
        "Valence electron number": 7,
        "Polarizability (a.u.)": 21.6, # Static dipole polarizability of neutral Br (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 111.7, # Enthalpy of atomization (1/2 Br2 -> Br)
        "Electron affinity (kJ/mol)": -324,
        "Atomic number": 35
    },
    "I": {
        "Ionic radius (pm)": 220, # I-
        "Electronegativity (Pauling)": 2.66,
        "Valence electron number": 7,
        "Polarizability (a.u.)": 32.9, # Static dipole polarizability of neutral I (a.u.) - Value from literature/tables (e.g., Schwerdtfeger & Nagle)
        "Atom formation enthalpy (kJ/mol)": 106.7, # Enthalpy of atomization (1/2 I2 -> I)
        "Electron affinity (kJ/mol)": -295,
        "Atomic number": 53
    }
}

## Bond dissociation energy (BDE)

In [ ]:
# @title Bond Energy of A-X

bond_energy_A_X = {
    "Li": {
        "F": 574.9,
        "Cl": 470.7,
        "Br": 423.0,
        "I": 352
    },
    "Na": {
        "F": 481.0,
        "Cl": 410.0,
        "Br": 370.0,
        "I": 301.0
    },
    "K": {
        "F": 497.5,
        "Cl": 425.9,
        "Br": 383.0,
        "I": 331.0
    },
    "Rb": {
        "F": 494.0,
        "Cl": 448.0,
        "Br": 389.0,
        "I": 335.0
    },
    "Cs": {
        "F": 514.0,
        "Cl": 439.0,
        "Br": 397.5,
        "I": 339.0
    },
    "Cu": {
        "F": 297.0,
        "Cl": 383.0,
        "Br": 331.0,
        "I": 197.0
    },
    "Au": {
        "F": None,
        "Cl": 343,
        "Br": None,
        "I": None
    },
    "Ag": {
        "F": 354.0,
        "Cl": 341.4,
        "Br": 293.0,
        "I": 234.0
    }
}

In [ ]:
# @title Bond Energy of B1-X
bond_energy_B1_X =bond_energy_B1_X = {
    "Pb": {
        "F": 356,
        "Cl": 301,
        "Br": 247,
        "I": 197
    },
    "Sn": {
        "F": 466.5,
        "Cl": 406,
        "Br": 326,
        "I": 234
    },
    "Ge": {
        "F": 485,
        "Cl": 431.8,
        "Br": 255,
        "I": None
    },
    "Be": {
        "F": 577,
        "Cl": 388,
        "Br": 381,
        "I": None
    },
    "Mg": {
        "F": 462,
        "Cl": 318,
        "Br": 297,
        "I": 285
    },
    "Ca": {
        "F": 527,
        "Cl": 398,
        "Br": 321,
        "I": 285
    },
    "Sr": {
        "F": 542,
        "Cl": 406,
        "Br": 332,
        "I": 263
    },
    "Ba": {
        "F": 487,
        "Cl": 444,
        "Br": 370,
        "I": 431
    },
    "Mn": {
        "F": 423,
        "Cl": 361,
        "Br": 314,
        "I": 283
    },
    "Fe": {
        "F": 394,
        "Cl": 352,
        "Br": 247,
        "I": None
    },
    "Co": {
        "F": 435,
        "Cl": 398,
        "Br": 331,
        "I": 235
    },
    "Ni": {
        "F": 435,
        "Cl": 367.9,
        "Br": 354.1,
        "I": 289
    },
    "Cu": {
        "F": 297,
        "Cl": 383,
        "Br": 331,
        "I": 197
    },
    "Zn": {
        "F": 368,
        "Cl": 229,
        "Br": 142,
        "I": 138
    },
    "Pd": {
        "F": None,
        "Cl": 238,
        "Br": None,
        "I": 253.6,
    },
    "Ir": {
        "F": None,         #uncertain
        "Cl": None,
        "Br": None,
        "I": None
    },
    "Pt": {
        "F": 435.3,       #NIST
        "Cl": 383,
        "Br": None,
        "I": None
    },
    "Te": {
        "F": 340,     #NIST 1970
        "Cl": 322,
        "Br": 297,
        "I": 193
    },
    "Cd": {
        "F": 305,
        "Cl": 206.7,
        "Br": 159,
        "I": 138
    }
}

In [ ]:
# @title Bond Energy B3-X

bond_energy_B3_X = {
    "Al": {
        "F": 664,
        "Cl": 494,
        "Br": 439,
        "I": 368
    },
    "Ga": {
        "F": 577,
        "Cl": 481,
        "Br": 444,
        "I": 339
    },
    "In": {
        "F": 506,
        "Cl": 439,
        "Br": 418,
        "I": None
    },
    "Sb": {
        "F": 439,
        "Cl": 360,
        "Br": 314,
        "I": None
    },
    "Bi": {
        "F": 259,
        "Cl": 305,
        "Br": 267,
        "I": None
    },
    "Au": {
        "F": None,
        "Cl": 343,
        "Br": None,
        "I": None
    },
    "Sc": {
        "F": 589,
        "Cl": 318,
        "Br": 444,
        "I": None
    },
    "Y": {
        "F": 605,
        "Cl": 527,
        "Br": 485,
        "I": None
    }
}

## Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_b3 = pd.read_csv("/content/drive/MyDrive/Colab-dataset/A2-B(I)-B'(III)-X6-All.csv")
df_b2 = pd.read_csv("/content/drive/MyDrive/Colab-dataset/A2-B(II)-B'(II)-X6-All.csv")

In [ ]:
df_b2.columns

Index(['material_id', 'formula', 'A', 'B1', 'B3', 'X', 'band_gap',
       'formation_energy_per_atom', 'e_above_hull'],
      dtype='object')

In [ ]:
df_b2.describe()

         band_gap  formation_energy_per_atom  e_above_hull
count  400.000000                 400.000000    400.000000
mean     2.446430                  -2.255495      0.061523
std      1.947043                   0.705280      0.147376
min      0.000000                  -3.741441      0.000000
25%      0.188375                  -2.779027      0.000040
50%      2.827050                  -2.442088      0.021469
75%      3.716075                  -1.623059      0.057885
max      7.061300                  -0.036181      1.378570

In [ ]:
df_b2[df_b2['e_above_hull']==0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 98 entries, 110 to 394
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   material_id                98 non-null     object
 1   formula                    98 non-null     object
 2   A                          98 non-null     object
 3   B1                         98 non-null     object
 4   B3                         98 non-null     object
 5   X                          98 non-null     object
 6   band_gap                   98 non-null     float64
 7   formation_energy_per_atom  98 non-null     float64
 8   e_above_hull               98 non-null     float64
dtypes: float64(3), object(6)
memory usage: 7.7+ KB

In [ ]:
df_b3[df_b3['e_above_hull']==0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 815
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   material_id                154 non-null    object
 1   formula                    154 non-null    object
 2   A                          154 non-null    object
 3   B1                         154 non-null    object
 4   B3                         154 non-null    object
 5   X                          154 non-null    object
 6   band_gap                   154 non-null    float64
 7   formation_energy_per_atom  154 non-null    float64
 8   e_above_hull               154 non-null    float64
dtypes: float64(3), object(6)
memory usage: 12.0+ KB

In [ ]:
df_b3.describe()

         band_gap  formation_energy_per_atom  e_above_hull
count  819.000000                 819.000000    819.000000
mean     2.667781                  -2.068721      0.084560
std      2.015084                   0.741774      0.140105
min      0.000000                  -3.602170      0.000000
25%      0.844950                  -2.686380      0.012244
50%      2.523200                  -1.928428      0.061880
75%      4.025650                  -1.459304      0.118735
max      8.319400                  -0.304083      2.277749

In [ ]:
# df_b2.drop(columns=['formation_energy_per_atom', 'e_above_hull'], inplace=True)

In [ ]:
for element, data in element_data.items():
    # Apply the changes only for specific rows
    if element in df_b2['A'].values:
      for index in df_b2[df_b2["A"] == element].index:
        df_b2.loc[index, "R-A(pm)"] = data["Ionic radius (pm)"]
        df_b2.loc[index, "I-A(kJ/mol)"] = data["Ionization energy (kJ/mol)"]
        df_b2.loc[index, "V-A"] = data["Valence electron number"]
        df_b2.loc[index, "P-A"] = data["Polarizability (a.u.)"]
        df_b2.loc[index, "E-A(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b2.loc[index, "N-A"] = data["Atomic number"]

In [ ]:
for element, data in element_data_2.items():
    # Apply the changes only for specific rows
    if element in df_b2['B1'].values:
      for index in df_b2[df_b2["B1"] == element].index:
        df_b2.loc[index, "R-B1(pm)"] = data["Ionic radius (pm)"]
        df_b2.loc[index, "X-B1(kJ/mol)"] = data["Electronegativity (Pauling)"]
        df_b2.loc[index, "V-B1"] = data["Valence electron number"]
        df_b2.loc[index, "P-B1"] = data["Polarizability (a.u.)"]
        df_b2.loc[index, "E-B1(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b2.loc[index, "N-B1"] = data["Atomic number"]

In [ ]:
for element, data in element_data_2.items():
    # Apply the changes only for specific rows
    if element in df_b2['B3'].values:
      for index in df_b2[df_b2["B3"] == element].index:
        df_b2.loc[index, "R-B3(pm)"] = data["Ionic radius (pm)"]
        df_b2.loc[index, "X-B3(kJ/mol)"] = data["Electronegativity (Pauling)"]
        df_b2.loc[index, "V-B3"] = data["Valence electron number"]
        df_b2.loc[index, "P-B3"] = data["Polarizability (a.u.)"]
        df_b2.loc[index, "E-B3(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b2.loc[index, "N-B3"] = data["Atomic number"]

In [ ]:
for element, data in element_data_4.items():
    # Apply the changes only for specific rows
    if element in df_b2['X'].values:
      for index in df_b2[df_b2["X"] == element].index:
        df_b2.loc[index, "R-X(pm)"] = data["Ionic radius (pm)"]
        df_b2.loc[index, "X-X(kJ/mol)"] = data["Electronegativity (Pauling)"]
        df_b2.loc[index, "V-X"] = data["Valence electron number"]
        df_b2.loc[index, "P-X"] = data["Polarizability (a.u.)"]
        df_b2.loc[index, "E-X(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b2.loc[index, "A-X(kJ/mol)"] = data["Electron affinity (kJ/mol)"]
        df_b2.loc[index, "N-X"] = data["Atomic number"]

In [ ]:
for element_a, data_a in bond_energy_A_X.items():
    for element_x, bond_energy in data_a.items():
        mask = (df_b2['A'] == element_a) & (df_b2['X'] == element_x)
        df_b2.loc[mask, 'BE(A-X)'] = bond_energy

In [ ]:
for element_a, data_a in bond_energy_B1_X.items():
    for element_x, bond_energy in data_a.items():
        mask = (df_b2['B1'] == element_a) & (df_b2['X'] == element_x)
        df_b2.loc[mask, 'BE(B1-X)'] = bond_energy

In [ ]:
for element_a, data_a in bond_energy_B1_X.items():
    for element_x, bond_energy in data_a.items():
        mask = (df_b2['B3'] == element_a) & (df_b2['X'] == element_x)
        df_b2.loc[mask, 'BE(B3-X)'] = bond_energy

In [ ]:
df_b2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   material_id                400 non-null    object
 1   formula                    400 non-null    object
 2   A                          400 non-null    object
 3   B1                         400 non-null    object
 4   B3                         400 non-null    object
 5   X                          400 non-null    object
 6   band_gap                   400 non-null    float64
 7   formation_energy_per_atom  400 non-null    float64
 8   e_above_hull               400 non-null    float64
 9   R-A(pm)                    400 non-null    float64
 10  I-A(kJ/mol)                400 non-null    float64
 11  V-A                        400 non-null    float64
 12  P-A                        400 non-null    float64
 13  E-A(kJ/mol)                400 non-null    float64
 14  N-A                        400 non-null    float64
 15  R-B1(pm)                   400 non-null    float64
 16  X-B1(kJ/mol)               400 non-null    float64
 17  V-B1                       400 non-null    float64
 18  P-B1                       400 non-null    float64
 19  E-B1(kJ/mol)               400 non-null    float64
 20  N-B1                       400 non-null    float64
 21  R-B3(pm)                   400 non-null    float64
 22  X-B3(kJ/mol)               400 non-null    float64
 23  V-B3                       400 non-null    float64
 24  P-B3                       400 non-null    float64
 25  E-B3(kJ/mol)               400 non-null    float64
 26  N-B3                       400 non-null    float64
 27  R-X(pm)                    400 non-null    float64
 28  X-X(kJ/mol)                400 non-null    float64
 29  V-X                        400 non-null    float64
 30  P-X                        400 non-null    float64
 31  E-X(kJ/mol)                400 non-null    float64
 32  A-X(kJ/mol)                400 non-null    float64
 33  N-X                        400 non-null    float64
 34  BE(A-X)                    400 non-null    float64
 35  BE(B1-X)                   378 non-null    float64
 36  BE(B3-X)                   378 non-null    float64
dtypes: float64(31), object(6)
memory usage: 115.8+ KB

In [ ]:
# df_b3.drop(columns=['formation_energy_per_atom', 'e_above_hull'], inplace=True)

In [ ]:
for element, data in element_data.items():
    # Apply the changes only for specific rows
    if element in df_b3['A'].values:
      for index in df_b3[df_b3["A"] == element].index:
        df_b3.loc[index, "R-A(pm)"] = data["Ionic radius (pm)"]
        df_b3.loc[index, "I-A(kJ/mol)"] = data["Ionization energy (kJ/mol)"]
        df_b3.loc[index, "V-A"] = data["Valence electron number"]
        df_b3.loc[index, "P-A"] = data["Polarizability (a.u.)"]
        df_b3.loc[index, "E-A(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b3.loc[index, "N-A"] = data["Atomic number"]

In [ ]:
for element, data in element_data.items():
    # Apply the changes only for specific rows
    if element in df_b3['B1'].values:
      for index in df_b3[df_b3["B1"] == element].index:
        df_b3.loc[index, "R-B1(pm)"] = data["Ionic radius (pm)"]
        # Putting Ionization value as Electronegetivity
        df_b3.loc[index, "X-B1(kJ/mol)"] = data["Ionization energy (kJ/mol)"]
        df_b3.loc[index, "V-B1"] = data["Valence electron number"]
        df_b3.loc[index, "P-B1"] = data["Polarizability (a.u.)"]
        df_b3.loc[index, "E-B1(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b3.loc[index, "N-B1"] = data["Atomic number"]

In [ ]:
for element, data in element_data_3.items():
    # Apply the changes only for specific rows
    if element in df_b3['B3'].values:
      for index in df_b3[df_b3["B3"] == element].index:
        df_b3.loc[index, "R-B3(pm)"] = data["Ionic radius (pm)"]
        df_b3.loc[index, "X-B3(kJ/mol)"] = data["Electronegativity (Pauling)"]
        df_b3.loc[index, "V-B3"] = data["Valence electron number"]
        df_b3.loc[index, "P-B3"] = data["Polarizability (a.u.)"]
        df_b3.loc[index, "E-B3(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b3.loc[index, "N-B3"] = data["Atomic number"]

In [ ]:
for element, data in element_data_4.items():
    # Apply the changes only for specific rows
    if element in df_b3['X'].values:
      for index in df_b3[df_b3["X"] == element].index:
        df_b3.loc[index, "R-X(pm)"] = data["Ionic radius (pm)"]
        df_b3.loc[index, "X-X(kJ/mol)"] = data["Electronegativity (Pauling)"]
        df_b3.loc[index, "V-X"] = data["Valence electron number"]
        df_b3.loc[index, "P-X"] = data["Polarizability (a.u.)"]
        df_b3.loc[index, "E-X(kJ/mol)"] = data["Atom formation enthalpy (kJ/mol)"]
        df_b3.loc[index, "A-X(kJ/mol)"] = data["Electron affinity (kJ/mol)"]
        df_b3.loc[index, "N-X"] = data["Atomic number"]

In [ ]:
for element_a, data_a in bond_energy_A_X.items():
    for element_x, bond_energy in data_a.items():
        mask = (df_b3['A'] == element_a) & (df_b3['X'] == element_x)
        df_b3.loc[mask, 'BE(A-X)'] = bond_energy

In [ ]:
for element_a, data_a in bond_energy_A_X.items():
    for element_x, bond_energy in data_a.items():
        mask = (df_b3['B1'] == element_a) & (df_b3['X'] == element_x)
        df_b3.loc[mask, 'BE(B1-X)'] = bond_energy

In [ ]:
for element_a, data_a in bond_energy_B3_X.items():
    for element_x, bond_energy in data_a.items():
        mask = (df_b3['B3'] == element_a) & (df_b3['X'] == element_x)
        df_b3.loc[mask, 'BE(B3-X)'] = bond_energy

In [ ]:
df_b3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 819 entries, 0 to 818
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   material_id                819 non-null    object
 1   formula                    819 non-null    object
 2   A                          819 non-null    object
 3   B1                         819 non-null    object
 4   B3                         819 non-null    object
 5   X                          819 non-null    object
 6   band_gap                   819 non-null    float64
 7   formation_energy_per_atom  819 non-null    float64
 8   e_above_hull               819 non-null    float64
 9   R-A(pm)                    819 non-null    float64
 10  I-A(kJ/mol)                819 non-null    float64
 11  V-A                        819 non-null    float64
 12  P-A                        819 non-null    float64
 13  E-A(kJ/mol)                819 non-null    float64
 14  N-A                        819 non-null    float64
 15  R-B1(pm)                   819 non-null    float64
 16  X-B1(kJ/mol)               819 non-null    float64
 17  V-B1                       819 non-null    float64
 18  P-B1                       819 non-null    float64
 19  E-B1(kJ/mol)               819 non-null    float64
 20  N-B1                       819 non-null    float64
 21  R-B3(pm)                   819 non-null    float64
 22  X-B3(kJ/mol)               819 non-null    float64
 23  V-B3                       819 non-null    float64
 24  P-B3                       819 non-null    float64
 25  E-B3(kJ/mol)               819 non-null    float64
 26  N-B3                       819 non-null    float64
 27  R-X(pm)                    819 non-null    float64
 28  X-X(kJ/mol)                819 non-null    float64
 29  V-X                        819 non-null    float64
 30  P-X                        819 non-null    float64
 31  E-X(kJ/mol)                819 non-null    float64
 32  A-X(kJ/mol)                819 non-null    float64
 33  N-X                        819 non-null    float64
 34  BE(A-X)                    819 non-null    float64
 35  BE(B1-X)                   742 non-null    float64
 36  BE(B3-X)                   668 non-null    float64
dtypes: float64(31), object(6)
memory usage: 236.9+ KB

In [ ]:
df_b3.to_csv("/content/drive/MyDrive/Colab-dataset/raw_data_b3.csv")
df_b2.to_csv("/content/drive/MyDrive/Colab-dataset/raw_data_b2.csv")